// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOfXJZlp03S7b0qlDZzUeWx0yid9WkA84',
    appId: '1:136905107328:web:da2c03228a50c235460365',
    messagingSenderId: '136905107328',
    projectId: 'motorby-2f353',
    authDomain: 'motorby-2f353.firebaseapp.com',
    storageBucket: 'motorby-2f353.appspot.com',
    measurementId: 'G-5C7952TH16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVATVkgxyMyy8mnQvf0_rSHbwnO2d4iCg',
    appId: '1:970650390015:android:df1b3410291f33963eabca',
    messagingSenderId: '970650390015',
    projectId: 'blinqpost',
    storageBucket: 'blinqpost.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNzmaHZYiPrTfV7Y6yQ40IsX_t-iwWYA',
    appId: '1:970650390015:ios:1a47a9e87b90e7743eabca',
     messagingSenderId: '970650390015',
    projectId: 'blinqpost',
    storageBucket: 'motorby-2f353.appspot.com',
    iosClientId: '136905107328-sfnsl6l8rk3khlj6qjgb1tq46jjrtf40.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileAutoDrive',
  );
}
